sudo: required

language: go
go:
  - 1.6

services:
  - docker

script:
  - docker-compose -f docker-compose.test.yml build
  - docker-compose -f docker-compose.test.yml up -d postgres
  - echo 'Waiting for postgres to have started up..'; sleep 30
  - docker-compose -f docker-compose.test.yml up user_api
