version: '2'
services:
  user_api:
    container_name: user_api
    build:
      context: .
      dockerfile: Dockerfile
    image: cc:user_api
    environment:
      CC_ENV: ${CC_ENV}
      CC_DBHOST: ${CC_DBHOST}
      CC_DBNAME: ${CC_DBNAME}
      CC_DBUSER: ${CC_DBUSER}
      CC_DBPASS: ${CC_DBPASS}
      CC_JWTSIGN: ${CC_JWTSIGN}
      CC_SPARKPOSTKEY: ${CC_SPARKPOSTKEY}
      AWS_REGION: ${AWS_REGION}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_BUCKET_SUBDIR: ${AWS_BUCKET_SUBDIR}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    links:
      - postgres
    ports:
      - 8082:8082

  postgres:
    container_name: postgres
    image: postgres:9.4.5
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: ${CC_DBUSER}
      POSTGRES_PASSWORD: ${CC_DBPASS}
      POSTGRES_DB: ${CC_DBNAME}
